// Core vocabulary word bank for "Oxford 3000 Adventure".
// Curated common-vocabulary word list organized by CEFR level (A1-B2), used as a
// selection FRAMEWORK inspired by the Oxford 3000 approach (most useful ~3000 words
// for learners, tagged by level) -- these are everyday words compiled independently,
// not a copy of Oxford University Press's proprietary word list or dictionary content.
// Shape matches the site's existing "database as JS array" convention (see exam-db.js).
//
// Each entry: { word, thai, pos, cefr, example, emoji }
//   pos: 'noun' | 'verb' | 'adjective' | 'adverb'
//   cefr: 'A1' | 'A2' | 'B1' | 'B2'
//   emoji: used as the lightweight "illustration" for picture-based games (no external
//          image hosting needed, consistent with the rest of the site's emoji art style)

const OXFORD_WORDS = [
  // ===================== A1 =====================
  { word: 'apple', thai: 'แอปเปิล', pos: 'noun', cefr: 'A1', example: 'I eat an apple.', emoji: '🍎' },
  { word: 'banana', thai: 'กล้วย', pos: 'noun', cefr: 'A1', example: 'The monkey likes a banana.', emoji: '🍌' },
  { word: 'orange', thai: 'ส้ม', pos: 'noun', cefr: 'A1', example: 'She drinks orange juice.', emoji: '🍊' },
  { word: 'bread', thai: 'ขนมปัง', pos: 'noun', cefr: 'A1', example: 'We eat bread for breakfast.', emoji: '🍞' },
  { word: 'milk', thai: 'นม', pos: 'noun', cefr: 'A1', example: 'The baby drinks milk.', emoji: '🥛' },
  { word: 'water', thai: 'น้ำ', pos: 'noun', cefr: 'A1', example: 'Please drink more water.', emoji: '💧' },
  { word: 'egg', thai: 'ไข่', pos: 'noun', cefr: 'A1', example: 'I have an egg for lunch.', emoji: '🥚' },
  { word: 'rice', thai: 'ข้าว', pos: 'noun', cefr: 'A1', example: 'We eat rice every day.', emoji: '🍚' },
  { word: 'cake', thai: 'เค้ก', pos: 'noun', cefr: 'A1', example: 'It is my birthday cake.', emoji: '🎂' },
  { word: 'fish', thai: 'ปลา', pos: 'noun', cefr: 'A1', example: 'The fish swims in water.', emoji: '🐟' },
  { word: 'cat', thai: 'แมว', pos: 'noun', cefr: 'A1', example: 'The cat is sleeping.', emoji: '🐱' },
  { word: 'dog', thai: 'สุนัข', pos: 'noun', cefr: 'A1', example: 'The dog is happy.', emoji: '🐶' },
  { word: 'bird', thai: 'นก', pos: 'noun', cefr: 'A1', example: 'A bird can fly.', emoji: '🐦' },
  { word: 'horse', thai: 'ม้า', pos: 'noun', cefr: 'A1', example: 'The horse runs fast.', emoji: '🐴' },
  { word: 'cow', thai: 'วัว', pos: 'noun', cefr: 'A1', example: 'The cow gives us milk.', emoji: '🐄' },
  { word: 'pig', thai: 'หมู', pos: 'noun', cefr: 'A1', example: 'The pig lives on a farm.', emoji: '🐷' },
  { word: 'duck', thai: 'เป็ด', pos: 'noun', cefr: 'A1', example: 'The duck swims in the pond.', emoji: '🦆' },
  { word: 'rabbit', thai: 'กระต่าย', pos: 'noun', cefr: 'A1', example: 'The rabbit likes carrots.', emoji: '🐰' },
  { word: 'lion', thai: 'สิงโต', pos: 'noun', cefr: 'A1', example: 'The lion is a big cat.', emoji: '🦁' },
  { word: 'elephant', thai: 'ช้าง', pos: 'noun', cefr: 'A1', example: 'The elephant is very big.', emoji: '🐘' },
  { word: 'monkey', thai: 'ลิง', pos: 'noun', cefr: 'A1', example: 'The monkey climbs the tree.', emoji: '🐵' },
  { word: 'boy', thai: 'เด็กชาย', pos: 'noun', cefr: 'A1', example: 'The boy is playing football.', emoji: '👦' },
  { word: 'girl', thai: 'เด็กหญิง', pos: 'noun', cefr: 'A1', example: 'The girl is reading a book.', emoji: '👧' },
  { word: 'mother', thai: 'แม่', pos: 'noun', cefr: 'A1', example: 'My mother cooks dinner.', emoji: '👩' },
  { word: 'father', thai: 'พ่อ', pos: 'noun', cefr: 'A1', example: 'My father drives a car.', emoji: '👨' },
  { word: 'sister', thai: 'พี่สาว/น้องสาว', pos: 'noun', cefr: 'A1', example: 'My sister is kind.', emoji: '👧' },
  { word: 'brother', thai: 'พี่ชาย/น้องชาย', pos: 'noun', cefr: 'A1', example: 'My brother is tall.', emoji: '👦' },
  { word: 'baby', thai: 'ทารก', pos: 'noun', cefr: 'A1', example: 'The baby is crying.', emoji: '👶' },
  { word: 'family', thai: 'ครอบครัว', pos: 'noun', cefr: 'A1', example: 'I love my family.', emoji: '👨‍👩‍👧' },
  { word: 'friend', thai: 'เพื่อน', pos: 'noun', cefr: 'A1', example: 'She is my best friend.', emoji: '🤝' },
  { word: 'teacher', thai: 'ครู', pos: 'noun', cefr: 'A1', example: 'The teacher is kind.', emoji: '👩‍🏫' },
  { word: 'student', thai: 'นักเรียน', pos: 'noun', cefr: 'A1', example: 'I am a student.', emoji: '🧑‍🎓' },
  { word: 'school', thai: 'โรงเรียน', pos: 'noun', cefr: 'A1', example: 'We go to school every day.', emoji: '🏫' },
  { word: 'book', thai: 'หนังสือ', pos: 'noun', cefr: 'A1', example: 'This is my book.', emoji: '📖' },
  { word: 'pen', thai: 'ปากกา', pos: 'noun', cefr: 'A1', example: 'I write with a pen.', emoji: '🖊️' },
  { word: 'pencil', thai: 'ดินสอ', pos: 'noun', cefr: 'A1', example: 'She draws with a pencil.', emoji: '✏️' },
  { word: 'bag', thai: 'กระเป๋า', pos: 'noun', cefr: 'A1', example: 'My bag is red.', emoji: '🎒' },
  { word: 'chair', thai: 'เก้าอี้', pos: 'noun', cefr: 'A1', example: 'Please sit on the chair.', emoji: '🪑' },
  { word: 'table', thai: 'โต๊ะ', pos: 'noun', cefr: 'A1', example: 'The book is on the table.', emoji: '🛏️' },
  { word: 'door', thai: 'ประตู', pos: 'noun', cefr: 'A1', example: 'Please close the door.', emoji: '🚪' },
  { word: 'house', thai: 'บ้าน', pos: 'noun', cefr: 'A1', example: 'This is my house.', emoji: '🏠' },
  { word: 'room', thai: 'ห้อง', pos: 'noun', cefr: 'A1', example: 'My room is small.', emoji: '🚪' },
  { word: 'bed', thai: 'เตียง', pos: 'noun', cefr: 'A1', example: 'The cat sleeps on the bed.', emoji: '🛏️' },
  { word: 'head', thai: 'หัว', pos: 'noun', cefr: 'A1', example: 'My head hurts a little.', emoji: '🗣️' },
  { word: 'hand', thai: 'มือ', pos: 'noun', cefr: 'A1', example: 'Wash your hands, please.', emoji: '✋' },
  { word: 'foot', thai: 'เท้า', pos: 'noun', cefr: 'A1', example: 'My foot is big.', emoji: '🦶' },
  { word: 'eye', thai: 'ตา', pos: 'noun', cefr: 'A1', example: 'She has big eyes.', emoji: '👁️' },
  { word: 'red', thai: 'สีแดง', pos: 'adjective', cefr: 'A1', example: 'The apple is red.', emoji: '🔴' },
  { word: 'blue', thai: 'สีฟ้า', pos: 'adjective', cefr: 'A1', example: 'The sky is blue.', emoji: '🔵' },
  { word: 'green', thai: 'สีเขียว', pos: 'adjective', cefr: 'A1', example: 'The grass is green.', emoji: '🟢' },
  { word: 'yellow', thai: 'สีเหลือง', pos: 'adjective', cefr: 'A1', example: 'The sun is yellow.', emoji: '🟡' },
  { word: 'black', thai: 'สีดำ', pos: 'adjective', cefr: 'A1', example: 'The cat is black.', emoji: '⚫' },
  { word: 'white', thai: 'สีขาว', pos: 'adjective', cefr: 'A1', example: 'Snow is white.', emoji: '⚪' },
  { word: 'one', thai: 'หนึ่ง', pos: 'noun', cefr: 'A1', example: 'I have one apple.', emoji: '1️⃣' },
  { word: 'two', thai: 'สอง', pos: 'noun', cefr: 'A1', example: 'I have two hands.', emoji: '2️⃣' },
  { word: 'three', thai: 'สาม', pos: 'noun', cefr: 'A1', example: 'There are three books.', emoji: '3️⃣' },
  { word: 'four', thai: 'สี่', pos: 'noun', cefr: 'A1', example: 'A table has four legs.', emoji: '4️⃣' },
  { word: 'five', thai: 'ห้า', pos: 'noun', cefr: 'A1', example: 'I have five fingers.', emoji: '5️⃣' },
  { word: 'six', thai: 'หก', pos: 'noun', cefr: 'A1', example: 'It is six o\'clock.', emoji: '6️⃣' },
  { word: 'seven', thai: 'เจ็ด', pos: 'noun', cefr: 'A1', example: 'There are seven days in a week.', emoji: '7️⃣' },
  { word: 'eight', thai: 'แปด', pos: 'noun', cefr: 'A1', example: 'A spider has eight legs.', emoji: '8️⃣' },
  { word: 'nine', thai: 'เก้า', pos: 'noun', cefr: 'A1', example: 'Nine plus one is ten.', emoji: '9️⃣' },
  { word: 'ten', thai: 'สิบ', pos: 'noun', cefr: 'A1', example: 'I have ten toes.', emoji: '🔟' },
  { word: 'sun', thai: 'ดวงอาทิตย์', pos: 'noun', cefr: 'A1', example: 'The sun is bright.', emoji: '☀️' },
  { word: 'moon', thai: 'ดวงจันทร์', pos: 'noun', cefr: 'A1', example: 'The moon shines at night.', emoji: '🌙' },
  { word: 'star', thai: 'ดวงดาว', pos: 'noun', cefr: 'A1', example: 'I can see a star.', emoji: '⭐' },
  { word: 'rain', thai: 'ฝน', pos: 'noun', cefr: 'A1', example: 'I hear the rain.', emoji: '🌧️' },
  { word: 'tree', thai: 'ต้นไม้', pos: 'noun', cefr: 'A1', example: 'A bird sits on the tree.', emoji: '🌳' },
  { word: 'flower', thai: 'ดอกไม้', pos: 'noun', cefr: 'A1', example: 'The flower smells nice.', emoji: '🌸' },
  { word: 'sky', thai: 'ท้องฟ้า', pos: 'noun', cefr: 'A1', example: 'The sky is blue today.', emoji: '🌤️' },
  { word: 'run', thai: 'วิ่ง', pos: 'verb', cefr: 'A1', example: 'I run to school.', emoji: '🏃' },
  { word: 'jump', thai: 'กระโดด', pos: 'verb', cefr: 'A1', example: 'The rabbit can jump high.', emoji: '🦘' },
  { word: 'eat', thai: 'กิน', pos: 'verb', cefr: 'A1', example: 'We eat rice every day.', emoji: '🍽️' },
  { word: 'drink', thai: 'ดื่ม', pos: 'verb', cefr: 'A1', example: 'I drink water.', emoji: '🥤' },
  { word: 'sleep', thai: 'นอนหลับ', pos: 'verb', cefr: 'A1', example: 'The baby sleeps a lot.', emoji: '😴' },
  { word: 'play', thai: 'เล่น', pos: 'verb', cefr: 'A1', example: 'Let\'s play together.', emoji: '🎮' },
  { word: 'read', thai: 'อ่าน', pos: 'verb', cefr: 'A1', example: 'I read a book every night.', emoji: '📚' },
  { word: 'write', thai: 'เขียน', pos: 'verb', cefr: 'A1', example: 'Please write your name.', emoji: '✍️' },
  { word: 'walk', thai: 'เดิน', pos: 'verb', cefr: 'A1', example: 'We walk to the park.', emoji: '🚶' },
  { word: 'sing', thai: 'ร้องเพลง', pos: 'verb', cefr: 'A1', example: 'She likes to sing.', emoji: '🎤' },
  { word: 'swim', thai: 'ว่ายน้ำ', pos: 'verb', cefr: 'A1', example: 'Fish can swim.', emoji: '🏊' },
  { word: 'look', thai: 'มอง', pos: 'verb', cefr: 'A1', example: 'Look at the sky!', emoji: '👀' },
  { word: 'big', thai: 'ใหญ่', pos: 'adjective', cefr: 'A1', example: 'The elephant is big.', emoji: '🐘' },
  { word: 'small', thai: 'เล็ก', pos: 'adjective', cefr: 'A1', example: 'The mouse is small.', emoji: '🐭' },
  { word: 'happy', thai: 'มีความสุข', pos: 'adjective', cefr: 'A1', example: 'I am happy today.', emoji: '😄' },
  { word: 'sad', thai: 'เศร้า', pos: 'adjective', cefr: 'A1', example: 'She looks sad.', emoji: '😢' },
  { word: 'hot', thai: 'ร้อน', pos: 'adjective', cefr: 'A1', example: 'The soup is hot.', emoji: '🥵' },
  { word: 'cold', thai: 'หนาว/เย็น', pos: 'adjective', cefr: 'A1', example: 'The ice is cold.', emoji: '🥶' },
  { word: 'new', thai: 'ใหม่', pos: 'adjective', cefr: 'A1', example: 'I have a new bag.', emoji: '🆕' },
  { word: 'old', thai: 'เก่า/แก่', pos: 'adjective', cefr: 'A1', example: 'This is an old book.', emoji: '📜' },
  { word: 'good', thai: 'ดี', pos: 'adjective', cefr: 'A1', example: 'You are a good friend.', emoji: '👍' },
  { word: 'car', thai: 'รถยนต์', pos: 'noun', cefr: 'A1', example: 'My father drives a car.', emoji: '🚗' },
  { word: 'bus', thai: 'รถบัส', pos: 'noun', cefr: 'A1', example: 'I go to school by bus.', emoji: '🚌' },
  { word: 'bike', thai: 'จักรยาน', pos: 'noun', cefr: 'A1', example: 'She rides a bike.', emoji: '🚲' },
  { word: 'ball', thai: 'ลูกบอล', pos: 'noun', cefr: 'A1', example: 'The boy kicks the ball.', emoji: '⚽' },
  { word: 'toy', thai: 'ของเล่น', pos: 'noun', cefr: 'A1', example: 'This is my favorite toy.', emoji: '🧸' },
  { word: 'box', thai: 'กล่อง', pos: 'noun', cefr: 'A1', example: 'Put the toys in the box.', emoji: '📦' },
  { word: 'phone', thai: 'โทรศัพท์', pos: 'noun', cefr: 'A1', example: 'My mother is using her phone.', emoji: '📱' },
  { word: 'clock', thai: 'นาฬิกา', pos: 'noun', cefr: 'A1', example: 'Look at the clock.', emoji: '🕐' },
  { word: 'shirt', thai: 'เสื้อ', pos: 'noun', cefr: 'A1', example: 'I wear a blue shirt.', emoji: '👕' },
  { word: 'shoes', thai: 'รองเท้า', pos: 'noun', cefr: 'A1', example: 'Put on your shoes.', emoji: '👟' },
  { word: 'hat', thai: 'หมวก', pos: 'noun', cefr: 'A1', example: 'She wears a red hat.', emoji: '🧢' },
  { word: 'window', thai: 'หน้าต่าง', pos: 'noun', cefr: 'A1', example: 'Open the window, please.', emoji: '🪟' },

  // ===================== A2 =====================
  { word: 'breakfast', thai: 'อาหารเช้า', pos: 'noun', cefr: 'A2', example: 'We eat breakfast at seven.', emoji: '🍳' },
  { word: 'lunch', thai: 'อาหารกลางวัน', pos: 'noun', cefr: 'A2', example: 'What do you have for lunch?', emoji: '🍱' },
  { word: 'dinner', thai: 'อาหารเย็น', pos: 'noun', cefr: 'A2', example: 'We have dinner together.', emoji: '🍛' },
  { word: 'kitchen', thai: 'ห้องครัว', pos: 'noun', cefr: 'A2', example: 'Mother is cooking in the kitchen.', emoji: '🍳' },
  { word: 'bathroom', thai: 'ห้องน้ำ', pos: 'noun', cefr: 'A2', example: 'I brush my teeth in the bathroom.', emoji: '🚿' },
  { word: 'bedroom', thai: 'ห้องนอน', pos: 'noun', cefr: 'A2', example: 'My bedroom is upstairs.', emoji: '🛌' },
  { word: 'garden', thai: 'สวน', pos: 'noun', cefr: 'A2', example: 'We grow flowers in the garden.', emoji: '🌷' },
  { word: 'weekend', thai: 'วันหยุดสุดสัปดาห์', pos: 'noun', cefr: 'A2', example: 'I play with friends on the weekend.', emoji: '🗓️' },
  { word: 'holiday', thai: 'วันหยุด', pos: 'noun', cefr: 'A2', example: 'We travel on holiday.', emoji: '🏖️' },
  { word: 'homework', thai: 'การบ้าน', pos: 'noun', cefr: 'A2', example: 'I do my homework every night.', emoji: '📝' },
  { word: 'subject', thai: 'วิชาเรียน', pos: 'noun', cefr: 'A2', example: 'Math is my favorite subject.', emoji: '📘' },
  { word: 'doctor', thai: 'หมอ', pos: 'noun', cefr: 'A2', example: 'The doctor helps sick people.', emoji: '🧑‍⚕️' },
  { word: 'nurse', thai: 'พยาบาล', pos: 'noun', cefr: 'A2', example: 'The nurse works at the hospital.', emoji: '👩‍⚕️' },
  { word: 'farmer', thai: 'ชาวนา/เกษตรกร', pos: 'noun', cefr: 'A2', example: 'The farmer grows rice.', emoji: '🧑‍🌾' },
  { word: 'driver', thai: 'คนขับรถ', pos: 'noun', cefr: 'A2', example: 'The bus driver is friendly.', emoji: '🚕' },
  { word: 'pilot', thai: 'นักบิน', pos: 'noun', cefr: 'A2', example: 'The pilot flies the airplane.', emoji: '✈️' },
  { word: 'singer', thai: 'นักร้อง', pos: 'noun', cefr: 'A2', example: 'My sister wants to be a singer.', emoji: '🎤' },
  { word: 'artist', thai: 'ศิลปิน', pos: 'noun', cefr: 'A2', example: 'The artist paints pictures.', emoji: '🎨' },
  { word: 'month', thai: 'เดือน', pos: 'noun', cefr: 'A2', example: 'There are twelve months in a year.', emoji: '📅' },
  { word: 'year', thai: 'ปี', pos: 'noun', cefr: 'A2', example: 'I am eight years old.', emoji: '📆' },
  { word: 'today', thai: 'วันนี้', pos: 'adverb', cefr: 'A2', example: 'Today is Monday.', emoji: '📍' },
  { word: 'tomorrow', thai: 'พรุ่งนี้', pos: 'adverb', cefr: 'A2', example: 'We have a test tomorrow.', emoji: '➡️' },
  { word: 'yesterday', thai: 'เมื่อวานนี้', pos: 'adverb', cefr: 'A2', example: 'It rained yesterday.', emoji: '⬅️' },
  { word: 'morning', thai: 'ตอนเช้า', pos: 'noun', cefr: 'A2', example: 'I wake up in the morning.', emoji: '🌅' },
  { word: 'evening', thai: 'ตอนเย็น', pos: 'noun', cefr: 'A2', example: 'We watch TV in the evening.', emoji: '🌆' },
  { word: 'night', thai: 'กลางคืน', pos: 'noun', cefr: 'A2', example: 'Stars shine at night.', emoji: '🌃' },
  { word: 'windy', thai: 'มีลมแรง', pos: 'adjective', cefr: 'A2', example: 'It is windy today.', emoji: '💨' },
  { word: 'cloudy', thai: 'มีเมฆมาก', pos: 'adjective', cefr: 'A2', example: 'The sky is cloudy.', emoji: '☁️' },
  { word: 'sunny', thai: 'แดดจัด', pos: 'adjective', cefr: 'A2', example: 'It is a sunny day.', emoji: '🌞' },
  { word: 'cook', thai: 'ทำอาหาร', pos: 'verb', cefr: 'A2', example: 'My father can cook well.', emoji: '👨‍🍳' },
  { word: 'clean', thai: 'ทำความสะอาด', pos: 'verb', cefr: 'A2', example: 'I clean my room every week.', emoji: '🧹' },
  { word: 'wash', thai: 'ล้าง', pos: 'verb', cefr: 'A2', example: 'Please wash your hands.', emoji: '🧼' },
  { word: 'buy', thai: 'ซื้อ', pos: 'verb', cefr: 'A2', example: 'We buy food at the market.', emoji: '🛒' },
  { word: 'sell', thai: 'ขาย', pos: 'verb', cefr: 'A2', example: 'The farmer sells vegetables.', emoji: '💰' },
  { word: 'learn', thai: 'เรียนรู้', pos: 'verb', cefr: 'A2', example: 'I learn English at school.', emoji: '🧠' },
  { word: 'teach', thai: 'สอน', pos: 'verb', cefr: 'A2', example: 'The teacher teaches math.', emoji: '👩‍🏫' },
  { word: 'help', thai: 'ช่วยเหลือ', pos: 'verb', cefr: 'A2', example: 'I help my mother at home.', emoji: '🤲' },
  { word: 'carry', thai: 'ถือ/แบก', pos: 'verb', cefr: 'A2', example: 'He carries a heavy bag.', emoji: '💪' },
  { word: 'catch', thai: 'จับ/รับ', pos: 'verb', cefr: 'A2', example: 'Catch the ball!', emoji: '🤾' },
  { word: 'climb', thai: 'ปีน', pos: 'verb', cefr: 'A2', example: 'The monkey climbs the tree.', emoji: '🧗' },
  { word: 'ride', thai: 'ขี่/นั่ง', pos: 'verb', cefr: 'A2', example: 'I ride my bike to school.', emoji: '🚴' },
  { word: 'drive', thai: 'ขับรถ', pos: 'verb', cefr: 'A2', example: 'My father drives to work.', emoji: '🚙' },
  { word: 'fly', thai: 'บิน', pos: 'verb', cefr: 'A2', example: 'Birds can fly high.', emoji: '🕊️' },
  { word: 'tall', thai: 'สูง', pos: 'adjective', cefr: 'A2', example: 'The giraffe is tall.', emoji: '🦒' },
  { word: 'short', thai: 'เตี้ย/สั้น', pos: 'adjective', cefr: 'A2', example: 'My pencil is short.', emoji: '📏' },
  { word: 'heavy', thai: 'หนัก', pos: 'adjective', cefr: 'A2', example: 'The box is heavy.', emoji: '🏋️' },
  { word: 'light', thai: 'เบา', pos: 'adjective', cefr: 'A2', example: 'The feather is light.', emoji: '🪶' },
  { word: 'strong', thai: 'แข็งแรง', pos: 'adjective', cefr: 'A2', example: 'The elephant is very strong.', emoji: '💪' },
  { word: 'beautiful', thai: 'สวยงาม', pos: 'adjective', cefr: 'A2', example: 'The flower is beautiful.', emoji: '🌺' },
  { word: 'quiet', thai: 'เงียบ', pos: 'adjective', cefr: 'A2', example: 'Please be quiet in the library.', emoji: '🤫' },
  { word: 'dirty', thai: 'สกปรก', pos: 'adjective', cefr: 'A2', example: 'My shoes are dirty.', emoji: '🥾' },
  { word: 'expensive', thai: 'แพง', pos: 'adjective', cefr: 'A2', example: 'The toy is expensive.', emoji: '💵' },
  { word: 'cheap', thai: 'ถูก', pos: 'adjective', cefr: 'A2', example: 'This book is cheap.', emoji: '🏷️' },
  { word: 'difficult', thai: 'ยาก', pos: 'adjective', cefr: 'A2', example: 'The test is difficult.', emoji: '🤯' },
  { word: 'easy', thai: 'ง่าย', pos: 'adjective', cefr: 'A2', example: 'This game is easy.', emoji: '😌' },
  { word: 'country', thai: 'ประเทศ', pos: 'noun', cefr: 'A2', example: 'Thailand is a beautiful country.', emoji: '🌏' },
  { word: 'city', thai: 'เมือง', pos: 'noun', cefr: 'A2', example: 'Bangkok is a big city.', emoji: '🏙️' },
  { word: 'river', thai: 'แม่น้ำ', pos: 'noun', cefr: 'A2', example: 'The river flows to the sea.', emoji: '🏞️' },
  { word: 'mountain', thai: 'ภูเขา', pos: 'noun', cefr: 'A2', example: 'We climb the mountain.', emoji: '⛰️' },
  { word: 'sea', thai: 'ทะเล', pos: 'noun', cefr: 'A2', example: 'We swim in the sea.', emoji: '🌊' },
  { word: 'beach', thai: 'ชายหาด', pos: 'noun', cefr: 'A2', example: 'We play at the beach.', emoji: '🏖️' },
  { word: 'forest', thai: 'ป่า', pos: 'noun', cefr: 'A2', example: 'Many animals live in the forest.', emoji: '🌲' },
  { word: 'birthday', thai: 'วันเกิด', pos: 'noun', cefr: 'A2', example: 'Happy birthday to you!', emoji: '🎉' },
  { word: 'present', thai: 'ของขวัญ', pos: 'noun', cefr: 'A2', example: 'I gave her a present.', emoji: '🎁' },
  { word: 'party', thai: 'งานเลี้ยง', pos: 'noun', cefr: 'A2', example: 'We had fun at the party.', emoji: '🎊' },
  { word: 'letter', thai: 'จดหมาย', pos: 'noun', cefr: 'A2', example: 'I wrote a letter to my friend.', emoji: '✉️' },
  { word: 'umbrella', thai: 'ร่ม', pos: 'noun', cefr: 'A2', example: 'Take an umbrella, it may rain.', emoji: '☂️' },
  { word: 'bicycle', thai: 'จักรยาน', pos: 'noun', cefr: 'A2', example: 'She rides her bicycle to school.', emoji: '🚲' },
  { word: 'airplane', thai: 'เครื่องบิน', pos: 'noun', cefr: 'A2', example: 'We travel by airplane.', emoji: '✈️' },
  { word: 'train', thai: 'รถไฟ', pos: 'noun', cefr: 'A2', example: 'The train arrives at nine.', emoji: '🚆' },
  { word: 'boat', thai: 'เรือ', pos: 'noun', cefr: 'A2', example: 'We cross the river by boat.', emoji: '⛵' },

  // ===================== B1 =====================
  { word: 'environment', thai: 'สิ่งแวดล้อม', pos: 'noun', cefr: 'B1', example: 'We must protect the environment.', emoji: '🌍' },
  { word: 'pollution', thai: 'มลพิษ', pos: 'noun', cefr: 'B1', example: 'Air pollution is bad for health.', emoji: '🏭' },
  { word: 'recycle', thai: 'รีไซเคิล/นำกลับมาใช้ใหม่', pos: 'verb', cefr: 'B1', example: 'We should recycle paper and bottles.', emoji: '♻️' },
  { word: 'temperature', thai: 'อุณหภูมิ', pos: 'noun', cefr: 'B1', example: 'The temperature is very high today.', emoji: '🌡️' },
  { word: 'climate', thai: 'สภาพภูมิอากาศ', pos: 'noun', cefr: 'B1', example: 'Thailand has a hot climate.', emoji: '🌦️' },
  { word: 'government', thai: 'รัฐบาล', pos: 'noun', cefr: 'B1', example: 'The government builds new schools.', emoji: '🏛️' },
  { word: 'education', thai: 'การศึกษา', pos: 'noun', cefr: 'B1', example: 'Education is important for everyone.', emoji: '🎓' },
  { word: 'technology', thai: 'เทคโนโลยี', pos: 'noun', cefr: 'B1', example: 'Technology changes our lives.', emoji: '💻' },
  { word: 'communication', thai: 'การสื่อสาร', pos: 'noun', cefr: 'B1', example: 'Phones help communication.', emoji: '📡' },
  { word: 'transportation', thai: 'การคมนาคมขนส่ง', pos: 'noun', cefr: 'B1', example: 'The bus is public transportation.', emoji: '🚉' },
  { word: 'agriculture', thai: 'เกษตรกรรม', pos: 'noun', cefr: 'B1', example: 'Agriculture is important in Thailand.', emoji: '🌾' },
  { word: 'population', thai: 'ประชากร', pos: 'noun', cefr: 'B1', example: 'The population of the city is growing.', emoji: '👥' },
  { word: 'culture', thai: 'วัฒนธรรม', pos: 'noun', cefr: 'B1', example: 'Thai culture is rich and colorful.', emoji: '🏮' },
  { word: 'tradition', thai: 'ประเพณี', pos: 'noun', cefr: 'B1', example: 'Songkran is a Thai tradition.', emoji: '🎎' },
  { word: 'celebration', thai: 'การเฉลิมฉลอง', pos: 'noun', cefr: 'B1', example: 'We had a big celebration.', emoji: '🎉' },
  { word: 'achievement', thai: 'ความสำเร็จ', pos: 'noun', cefr: 'B1', example: 'Winning the game was a great achievement.', emoji: '🏆' },
  { word: 'opportunity', thai: 'โอกาส', pos: 'noun', cefr: 'B1', example: 'This is a good opportunity to learn.', emoji: '🚪' },
  { word: 'experience', thai: 'ประสบการณ์', pos: 'noun', cefr: 'B1', example: 'Traveling gives you experience.', emoji: '🧳' },
  { word: 'responsibility', thai: 'ความรับผิดชอบ', pos: 'noun', cefr: 'B1', example: 'Cleaning my room is my responsibility.', emoji: '📋' },
  { word: 'confidence', thai: 'ความมั่นใจ', pos: 'noun', cefr: 'B1', example: 'She speaks with confidence.', emoji: '💪' },
  { word: 'imagination', thai: 'จินตนาการ', pos: 'noun', cefr: 'B1', example: 'Children have great imagination.', emoji: '💭' },
  { word: 'creativity', thai: 'ความคิดสร้างสรรค์', pos: 'noun', cefr: 'B1', example: 'Art needs creativity.', emoji: '🎨' },
  { word: 'honesty', thai: 'ความซื่อสัตย์', pos: 'noun', cefr: 'B1', example: 'Honesty is an important value.', emoji: '🤝' },
  { word: 'patience', thai: 'ความอดทน', pos: 'noun', cefr: 'B1', example: 'Learning a language needs patience.', emoji: '⏳' },
  { word: 'courage', thai: 'ความกล้าหาญ', pos: 'noun', cefr: 'B1', example: 'It takes courage to try new things.', emoji: '🦁' },
  { word: 'adventure', thai: 'การผจญภัย', pos: 'noun', cefr: 'B1', example: 'We went on a fun adventure.', emoji: '🗺️' },
  { word: 'journey', thai: 'การเดินทาง', pos: 'noun', cefr: 'B1', example: 'The journey to the city was long.', emoji: '🧭' },
  { word: 'destination', thai: 'จุดหมายปลายทาง', pos: 'noun', cefr: 'B1', example: 'Our destination is the beach.', emoji: '📍' },
  { word: 'competition', thai: 'การแข่งขัน', pos: 'noun', cefr: 'B1', example: 'She won the singing competition.', emoji: '🥇' },
  { word: 'invention', thai: 'สิ่งประดิษฐ์', pos: 'noun', cefr: 'B1', example: 'The telephone was a great invention.', emoji: '💡' },
  { word: 'discovery', thai: 'การค้นพบ', pos: 'noun', cefr: 'B1', example: 'Scientists made a new discovery.', emoji: '🔬' },

  // ===================== B2 =====================
  { word: 'sustainability', thai: 'ความยั่งยืน', pos: 'noun', cefr: 'B2', example: 'Sustainability protects our future.', emoji: '🌱' },
  { word: 'biodiversity', thai: 'ความหลากหลายทางชีวภาพ', pos: 'noun', cefr: 'B2', example: 'The rainforest has amazing biodiversity.', emoji: '🦋' },
  { word: 'globalization', thai: 'โลกาภิวัตน์', pos: 'noun', cefr: 'B2', example: 'Globalization connects countries together.', emoji: '🌐' },
  { word: 'infrastructure', thai: 'โครงสร้างพื้นฐาน', pos: 'noun', cefr: 'B2', example: 'The city needs better infrastructure.', emoji: '🏗️' },
  { word: 'entrepreneur', thai: 'ผู้ประกอบการ', pos: 'noun', cefr: 'B2', example: 'The entrepreneur started a new business.', emoji: '💼' },
  { word: 'philosophy', thai: 'ปรัชญา', pos: 'noun', cefr: 'B2', example: 'She studies philosophy at university.', emoji: '🤔' },
  { word: 'psychology', thai: 'จิตวิทยา', pos: 'noun', cefr: 'B2', example: 'Psychology helps us understand people.', emoji: '🧠' },
  { word: 'democracy', thai: 'ประชาธิปไตย', pos: 'noun', cefr: 'B2', example: 'Thailand is a democracy.', emoji: '🗳️' },
  { word: 'negotiation', thai: 'การเจรจาต่อรอง', pos: 'noun', cefr: 'B2', example: 'The negotiation took several hours.', emoji: '🤝' },
  { word: 'controversy', thai: 'ข้อโต้แย้ง', pos: 'noun', cefr: 'B2', example: 'The plan caused a lot of controversy.', emoji: '⚖️' },
  { word: 'phenomenon', thai: 'ปรากฏการณ์', pos: 'noun', cefr: 'B2', example: 'A rainbow is a beautiful phenomenon.', emoji: '🌈' },
  { word: 'hypothesis', thai: 'สมมติฐาน', pos: 'noun', cefr: 'B2', example: 'The scientist tested her hypothesis.', emoji: '🔬' },
  { word: 'consequence', thai: 'ผลที่ตามมา', pos: 'noun', cefr: 'B2', example: 'Every choice has a consequence.', emoji: '⚡' },
  { word: 'perspective', thai: 'มุมมอง', pos: 'noun', cefr: 'B2', example: 'Try to see it from her perspective.', emoji: '🔍' },
  { word: 'significant', thai: 'สำคัญมาก', pos: 'adjective', cefr: 'B2', example: 'This was a significant discovery.', emoji: '❗' },
  { word: 'inevitable', thai: 'หลีกเลี่ยงไม่ได้', pos: 'adjective', cefr: 'B2', example: 'Change is inevitable.', emoji: '⏭️' },
  { word: 'controversial', thai: 'เป็นที่ถกเถียง', pos: 'adjective', cefr: 'B2', example: 'It was a controversial decision.', emoji: '💬' },
  { word: 'ambiguous', thai: 'คลุมเครือ', pos: 'adjective', cefr: 'B2', example: 'His answer was ambiguous.', emoji: '❓' },
  { word: 'innovative', thai: 'มีความคิดริเริ่ม', pos: 'adjective', cefr: 'B2', example: 'It was an innovative idea.', emoji: '💡' },
  { word: 'independence', thai: 'ความเป็นอิสระ', pos: 'noun', cefr: 'B2', example: 'The country celebrates its independence.', emoji: '🕊️' }
];

// Small helpers shared by the Oxford Adventure page.
const OxfordWords = {
  all: OXFORD_WORDS,
  byLevel(cefr) { return OXFORD_WORDS.filter(w => w.cefr === cefr); },
  // Splits the whole ordered word bank into fixed-size "stages" (default 10 words each).
  // Levels are generated from however many words exist today, so the map grows
  // automatically as more words are added to OXFORD_WORDS later.
  stages(size = 10) {
    const out = [];
    for (let i = 0; i < OXFORD_WORDS.length; i += size) {
      out.push(OXFORD_WORDS.slice(i, i + size));
    }
    return out;
  }
};
